### ISSUE TITLE
.NET Aspire Docs: Go-live checklist

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/docs-aspire#9]
## Before .NET Conf

- [x] .NET Aspire repositories that go public:
  - [x] https://github.com/dotnet/aspire
  - [x] https://github.com/dotnet/aspire-samples
  - [x] https://github.com/dotnet/docs-aspire
  - [ ] ~https://github.com/dotnet/aspire-api-docs~
- [x] Update all [aka.ms links](https://redirectiontool.trafficmanager.net/am/redirection/home?options=host:aka.ms&set=enableReadOnlyLinks) with live URLs:
  - [x] .NET Aspire hub: https://aka.ms/dotnet/aspire/docs
  - [x] .NET Aspire overview: https://aka.ms/dotnet/aspire/docs/overview
  - [x] .NET Aspire components: https://aka.ms/dotnet/aspire/components
  - [x] .NET Aspire dashboard: https://aka.ms/dotnet/aspire/docs/dashboard
- [x] Content: Merge .NET Aspire additions in `dotnet/docs`.
- [x] .NET Aspire is added to learn.microsoft.com Product directory and .NET Workload dropdown:
  - [x] https://github.com/MicrosoftDocs/DocsRoot/pull/1752
  - [ ] ~https://github.com/MicrosoftDocs/DocsRoot/pull/1753~
- [x] dotnet/aspire-api-docs (in `live`):
  - [x] https://github.com/dotnet/aspire-api-docs/pull/1
  - [x] https://github.com/dotnet/aspire-api-docs/pull/2

## Post .NET Conf

- [ ] dotnet/aspire-samples: When this goes public, it can take up to 72 hours for samples to flow into the [Browse code samples: .NET Aspire](https://learn.microsoft.com/en-us/samples/browse/?terms=aspire).
- [x] Update all .NET Aspire docs to use .NET Aspire API reference, `xref` within conceptual docs. This is blocked by `dotnet/aspire-api-docs` not being public.
